from setuptools import setup, find_packages

setup(
    name="florisboard-api",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "fastapi>=0.95.0",
        "uvicorn[standard]>=0.21.0",
        "sqlalchemy>=2.0.0",
        "alembic>=1.10.0",
        "psycopg2-binary>=2.9.5",
        "python-jose[cryptography]>=3.3.0",
        "passlib[bcrypt]>=1.7.4",
        "python-multipart>=0.0.6",
        "pydantic>=1.10.0",
        "email-validator>=1.3.0",
        "requests>=2.28.0",
        "aiohttp>=3.8.4",
        "python-dotenv>=1.0.0",
        "tenacity>=8.2.0",
        "httpx>=0.23.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "black>=23.0.0",
            "isort>=5.12.0",
            "mypy>=1.0.0",
        ],
    },
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    description="REST API for FlorisBoard Game and Discord Enhancement",
    keywords="keyboard, discord, game, api",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)